services:
  app:
    image: node:22-alpine
    working_dir: /app/admin
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    network_mode: host
    #ports:
    #  - "5173:5173"
