user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr warn;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    js_import portal from /etc/nginx/njs/portal.js;

    log_format track_main
        '$time_iso8601\t'
        '$remote_addr\t'
        '$request_method\t'
        '$request_uri\t'
        '$status\t'
        '$body_bytes_sent\t'
        '$http_user_agent\t'
        '$http_referer\t'
        '$http_accept_language';

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    gzip on;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
